services:
  - type: web
    name: frontend
    runtime: static
    rootDir: frontend
    buildCommand: cd .. && npm install && npm run build && cp -r dist frontend/dist
    staticPublishPath: ./dist
    envVars:
      - key: NODE_VERSION
        value: 22.14.0
