services:
  - type: web
    name: frontend
    buildCommand: cd frontend && npm install && npm run build
    startCommand: cd frontend && node server.js
    envVars:
      - key: NODE_VERSION
        value: 18.18.0
      - key: PORT
        value: 5173
