services:
  - type: web
    name: frontend
    runtime: static
    buildCommand: npm ci && npm run build
    staticPublishPath: ./dist
    envVars:
      - key: NODE_VERSION
        value: 22
      - key: PORT
        value: 5173
    headers:
      - path: /*
        name: Cache-Control
        value: no-store
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
