name: Build and Deploy
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Ensure _redirects file exists
        run: |
          mkdir -p dist
          echo "/* /index.html 200" > dist/_redirects

      - name: Deploy to Render
        run: |
          echo "Build completed and ready for deployment"
          echo "Note: Deployment is handled by Render's auto-deploy integration with GitHub" 